### ISSUE TITLE
Hash function for DES time structs

### ISSUE THREAD

**Issue by romancardenas** [SimulationEverywhere/DESTimes#4]
Hi everyone!

I'm trying to use `NDTime` for Cadmium Cell-DEVS projects.
One piece of the code uses unordered dictionaries to schedule events. Therefore, I need a hashing function for the time struct that the model uses to represent time (maybe with [`boost::hash_combine`](http://www.boost.org/doc/libs/release/doc/html/hash/reference.html#boost.hash_combine)?).

I don't mind doing it myself, but if any of you wants to get this issue assigned, I'm OK as well.

Regards!

**Comment by Laouen** [comment]
Sounds good for me, go-ahead from my part
